<?xml version="1.0" encoding="UTF_8" ?>
<xsl:stylesheet  xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:svg="http://www.w3.org/2000/svg"  xmlns:math="http://exslt.org/math" xmlns:xlink="http://www.w3.org/1999/xlink" extension-element-prefixes="math" version="1.0" >

<xsl:output method="text" omit-xml-declaration="yes" indent="no"/>

<xsl:variable name="categories" select="document('../categories.xml')"/>
<xsl:variable name="colors" select="document('../colors.xml')"/>
<xsl:param name="side"/>
<xsl:param name="orient"/>
<!--<xsl:param name="size"/>-->
<!--<xsl:param name="font"/>-->

<xsl:template match="/">
#---- Generated by tint2conf 914e ----
# See https://gitlab.com/o9000/tint2/wikis/Configure for 
# full documentation of the configuration options.
#-------------------------------------
# Gradients
#-------------------------------------
# Backgrounds

<xsl:apply-templates select="$categories/categories/category"/>


# Background 99: Tooltip
rounded = 1
border_width = 1
border_sides = TBLR
border_content_tint_weight = 0
background_content_tint_weight = 0
background_color = #222222 100
border_color = #333333 100
background_color_hover = #ffffaa 100
border_color_hover = #000000 100
background_color_pressed = #ffffaa 100
border_color_pressed = #000000 100

#-------------------------------------
# Panel
panel_items = <xsl:for-each select="panel/subpanel/items/*"><xsl:value-of select="@brief"/></xsl:for-each>
panel_size = <xsl:value-of select="panel/@size"/>
panel_margin = 0 0
panel_padding = 2 0 2
panel_background_id = 1
wm_menu = 1
panel_dock = 0
#panel_pivot_struts = 0
#vpos hpos orient
panel_position = <xsl:value-of select="panel/@vside"/><xsl:text> </xsl:text> <xsl:value-of select="panel/@hside"/><xsl:text> </xsl:text> <xsl:value-of select="panel/@orient"/>
panel_layer = top
panel_monitor = all
panel_shrink = 0
autohide = 0
autohide_show_timeout = 0
autohide_hide_timeout = 0.5
autohide_height = 2
strut_policy = follow_size
panel_window_name = tint2
disable_transparency = 1
mouse_effects = 1
font_shadow = 0
mouse_hover_icon_asb = 100 0 10
mouse_pressed_icon_asb = 100 0 0
scale_relative_to_dpi = 0
scale_relative_to_screen_height = 0

<xsl:apply-templates select="panel/subpanel/items/*"/>

#-------------------------------------
# Tooltip
tooltip_show_timeout = 0.3
tooltip_hide_timeout = 0.1
tooltip_padding = 4 4
tooltip_background_id = 99
tooltip_font_color = #dddddd 100

</xsl:template>

<xsl:template match="executor">
#-------------------------------------
# Executor <xsl:value-of select="position()"/>
execp = new
execp_command = <xsl:value-of select="command"/>
execp_interval = <xsl:value-of select="interval"/>
execp_has_icon = 1
execp_cache_icon = 0
execp_continuous = 0
execp_markup = 0
execp_lclick_command = <xsl:value-of select="click_command"/>
execp_rclick_command = 
execp_mclick_command = 
execp_uwheel_command = 
execp_dwheel_command = 
execp_font = Sans 26
execp_font_color = #ffffff 100
execp_padding = 0 0
execp_background_id = 0
execp_centered = 0
execp_icon_w = 0
execp_icon_h = 0
</xsl:template>

<xsl:template match="launcher">
#-------------------------------------
# Launcher
launcher_padding = 2 4 2
launcher_background_id = 0
launcher_icon_background_id = 0
#launcher_icon_size = 45
launcher_icon_asb = 100 0 0
launcher_icon_theme_override = 1
startup_notifications = 1
launcher_tooltip = 1
launcher_apps_dir = ~/Projects/SOFT/BASH/panel/apps/launchers/tint
</xsl:template>

<xsl:template match="systray">
#-------------------------------------
# System tray (notification area)
systray_padding = 0 4 2
systray_background_id = 0
systray_sort = ascending
systray_icon_size = 45
systray_icon_asb = 100 0 0
systray_monitor = 1
systray_name_filter = 
</xsl:template>
<xsl:template match="clock">
#-------------------------------------
# Clock
time1_format = %H:%M
time2_format = %d %B
time1_font = Sans Bold 16
time1_timezone = 
time2_timezone = 
time2_font = Sans 12
clock_font_color = #ffffff 100
clock_padding = 2 0
clock_background_id = 0
clock_tooltip = 
clock_tooltip_timezone = 
clock_lclick_command = lxterminal  --geometry=70x38  -e &quot;cal -y &amp;&amp; read -n 1 c&quot;
clock_rclick_command = 
clock_mclick_command = 
clock_uwheel_command = 
clock_dwheel_command = 
</xsl:template>

<xsl:template match="separator">
#-------------------------------------
# Separator <xsl:value-of select="position()"/>
separator = new
separator_background_id = 0
separator_color = #777777 89
separator_style =  <xsl:value-of select="style"/>
separator_size = <xsl:value-of select="size"/>
separator_padding = 1 0
</xsl:template>

<xsl:template match="taskbar">
#-------------------------------------
# Task
task_text = 0
task_icon = 1
task_centered = 1
urgent_nb_of_blink = 100000
task_maximum_size = 150 40
task_padding = 2 2 4
task_tooltip = 1
task_thumbnail = 1
task_thumbnail_size = 210
task_font_color = #ffffff 100
task_background_id = 1
task_active_background_id = <xsl:value-of select="count($categories/categories/category[@type = 'Active Task']/preceding-sibling::*) + 1"/>
task_urgent_background_id = <xsl:value-of select="count($categories/categories/category[@type = 'Urgent Task']/preceding-sibling::*) + 1"/>
task_iconified_background_id = 2
mouse_left = toggle_iconify
mouse_middle = none
mouse_right = close
mouse_scroll_up = toggle
mouse_scroll_down = iconify
</xsl:template>

<xsl:template match="button">
<xsl:variable name="cat" select="../../@category"/>
<xsl:variable name="fore" select="$categories/categories/category[@name = $cat]/@fore"/>
<xsl:variable name="font" select="$categories/categories/category[@name = $cat]/@font"/>
#-------------------------------------
# Button <xsl:value-of select="position()"/>
button = <xsl:value-of select="name"/>

button_text =  <xsl:value-of select="display"/>

button_icon = <xsl:value-of select="icon"/>
button_lclick_command =  <xsl:value-of select="command"/>
button_font = <xsl:value-of select="$font"/>
button_font_color =  <xsl:value-of select="$colors/colors/color[@name = $fore]"/> 100
button_padding = 2 0
button_background_id =  <xsl:value-of select="count($categories/categories/category[@name = $cat]/preceding-sibling::*) + 1"/>
button_centered = 0
button_max_icon_size = 0

</xsl:template>

<xsl:template match="categories/category">
<xsl:variable name="back" select="@back"/>
<xsl:variable name="fore" select="@fore"/>
# Background <xsl:value-of select="position()"/>: <xsl:value-of select="@type"/>
rounded = 4
border_width = 1
border_sides = TBLR
border_content_tint_weight = 0
background_content_tint_weight = 0
background_color = <xsl:value-of select="$colors/colors/color[@name = $back]"/> 100
border_color = <xsl:value-of select="$colors/colors/color[@name = $back]"/> 100
background_color_hover = #AAAAAA 100
border_color_hover = #222222 100
background_color_pressed = #555555 4
border_color_pressed = #555555 4

</xsl:template>
</xsl:stylesheet>
